# Generated by Django 5.2.7 on 2025-10-25 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_trips', to='trip_planner.location'),
        ),
        migrations.AddField(
            model_name='routesegment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='trip_planner.trip'),
        ),
        migrations.AddField(
            model_name='reststop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_stops', to='trip_planner.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='routesegment',
            unique_together={('trip', 'sequence')},
        ),
    ]
