# Generated by Django 5.2.7 on 2025-10-25 01:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_date', models.DateField()),
                ('cycle_type', models.CharField(choices=[('70_8', '70/8 Hour Cycle'), ('60_7', '60/7 Hour Cycle'), ('34_hour', '34-Hour Restart')], default='70_8', max_length=20)),
                ('hours_used_this_cycle', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('70.00'))])),
                ('hours_available', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('70.00'))])),
                ('consecutive_off_duty_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('last_30_min_break', models.DateTimeField(blank=True, null=True)),
                ('can_drive', models.BooleanField(default=True)),
                ('can_be_on_duty', models.BooleanField(default=True)),
                ('needs_rest', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cycle Status',
                'verbose_name_plural': 'Cycle Statuses',
                'db_table': 'cycle_statuses',
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('total_driving_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('11.00'))])),
                ('total_on_duty_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('14.00'))])),
                ('total_off_duty_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('has_violations', models.BooleanField(default=False)),
                ('violation_details', models.TextField(blank=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('certification_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'db_table': 'daily_logs',
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty - Not Driving')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Duty Status',
                'verbose_name_plural': 'Duty Statuses',
                'db_table': 'duty_statuses',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('24.00'))])),
                ('location', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('remarks', models.TextField(blank=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'log_entries',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('driving_over_11', 'Driving Over 11 Hours'), ('on_duty_over_14', 'On Duty Over 14 Hours'), ('insufficient_rest', 'Insufficient Rest'), ('no_30_min_break', 'No 30-Minute Break'), ('driving_after_14', 'Driving After 14 Hours'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=10)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('duration_over', models.DurationField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'db_table': 'violations',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
