# Generated by Django 5.2.7 on 2025-10-25 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_sheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclestatus',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logentry',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logentry',
            name='duty_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='log_sheets.dutystatus'),
        ),
        migrations.AddField(
            model_name='violation',
            name='daily_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='log_sheets.dailylog'),
        ),
        migrations.AddField(
            model_name='violation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('driver', 'log_date')},
        ),
        migrations.AlterUniqueTogether(
            name='logentry',
            unique_together={('driver', 'start_time', 'end_time')},
        ),
    ]
